spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_management
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 900087453526-t9dmt7d7temari2diuud2hia8noh0v92.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id:  907038
            client-secret: 215726fb5b81e6f4b5a0082c10f26b13
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - account_email
          naver:
            client-id: CZi71_X5DdgjKLgxAFHu
            client-secret: _ninGfWfGI
            redirect-uri:  http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
              
mybatis:
  mapper-locations:
    - /mappers/*.xml 
    
jwt:
  secret: qJzUmGueQXDTxcXJyWUZa2oVwieBrVF41ozvRaHcW4uJ8Y4sJqHQC8WbvNoTC63k
